### ISSUE TITLE
Error while decompiling APK

### ISSUE THREAD

**Issue by yashwanthkorla** [dwisiswant0/apkleaks#14]
Hi,

Script is failing while decompiling apk. Tested with multiple apk's.

![image](https://user-images.githubusercontent.com/4706215/110215260-c0539d00-7ece-11eb-8bd8-8d6e5d567044.png)

**Comment by dwisiswant0** [comment]
Is that stopped at decompiling process, @yashwanthkorla?

**Comment by yashwanthkorla** [comment]
Yes, os.system(commnad) call is failing.

**Comment by dwisiswant0** [comment]
Are you sure, @yashwanthkorla? Because I also experienced it during decompiling process but it didn't interrupt scanning process. Please don't crop your proof 'til next tty input (if its interrupted).

![Screenshot_2021-03-07_01-13-20](https://user-images.githubusercontent.com/25837540/110216576-66f56900-7ee2-11eb-9a09-141edf1d821c.png)

**Comment by yashwanthkorla** [comment]
@dwisiswant0 , it didn't interrupt the scanning process, but I couldn't see any output. 

![image](https://user-images.githubusercontent.com/4706215/110216864-8b981380-7ed7-11eb-8395-533114fe19bc.png)

If no info comes up after scanning, does it mean no information to be found?

**Comment by dwisiswant0** [comment]
I can't answer that, since we use default log-level of jadx (which is `PROGRESS`). I'll investigate this along with #15 issue.
